### ISSUE TITLE
Demo notebook cell 5 error (maybe matplotlib?)

### ISSUE THREAD

**Issue by snehavdixit** [alexander-held/calver-coffea-agc-demo#3]
Setup : 
awkward: 2.6.3
dask-awkward: 2024.3.0
uproot: 5.3.2
hist: 2.7.2
coffea: 2024.4.0

Cell In[5], line 5
5 ax = artists[0].stairs.axes
AttributeError: 'list' object has no attribute 'stairs'

**Comment by alexander-held** [comment]
Thanks for following up on this! I cannot reproduce the issue currently on coffea-opendata with the latest version of the notebook. Is there a a chance you ran the cells in a different order maybe or did you perhaps have other changes to the notebook that may cause issues? Please give it another try with a clean version of the notebook and all cells in order.

**Comment by snehavdixit** [comment]
Tried again with a clean version - the error isn't there anymore. Sorry for the inconvenience!

**Comment by alexander-held** [comment]
No worries, glad to hear it is working!
